name: lobbygames
version: '${version}'

main: me.colinstudios.lobbygames.Lobbygames
api-version: '1.21.11'
load: POSTWORLD
softdepend:
  - PlaceholderAPI
commands:
  cookie:
    description: CookieClicker Admin-Verwaltung
    usage: /cookie admin <set|info|add|remove|reset|specialitem|reloadhologram|reloadleaderboard>
    permission: lobbygames.cookieadmin
permissions:
  lobbygames.cookieadmin:
    description: Erlaubt die Verwaltung des CookieClickers
    default: op
